Track-1/client

.eslintrc
=> [ etc ] esLint & prettier 설정

src/@components/@common/portfoliosInform.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@pages/producerProfilePage.tsx, src/mocks/handlers/producerProfile.ts
producerProfile 페이지에 플레이어 병합했습니다.
=> Feat#56 common/refactor

src/@components/producerProfile/producerInfos.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/trackPost/userComment.tsx, src/@pages/producerProfilePage.tsx
왼쪽 profile fixed로 고정함
position : fixed
, 오른쪽 container 다시 감싸서 margin값으로 위치 조정
https://user-images.githubusercontent.com/88815795/211988942-2948d1bf-66e8-4485-9f04-b52d9d6a0059.mp4
pr 남길때, base로 develop으로 보내는 건가? 일단 그렇게 올립니당
=> [ trackPost ] - 무한스크롤 

src/@components/@common/portfoliosInform.tsx, src/@components/@common/uploadHeader.tsx, src/core/api/vocalProfile.ts
리팩토링 진행했습니다. 릴리즈브랜치에서 이어서 진행할께요.
=> Feat#93 common/refactor

src/@components/@common/categoryList.tsx, src/@components/@common/uploadHeader.tsx, src/@components/trackSearch/uploadButtonModal.tsx, src/@pages/uploadPage.tsx, src/Router.tsx
- useRef를 이용해서 모달 바깥을 클릭하면 모달이 닫히도록 했어요
=> Feat#100-QA/trackUpload

src/@components/@common/categoryHeader.tsx, src/@components/@common/categoryList.tsx, src/@components/@common/portfoliosInform.tsx, src/@pages/vocalProfilePage.tsx
- 보컬인지 프로듀서인지에 따라 마이페이지 연결 수정
- 보컬이면 업로드 버튼이 등장하지 않도록 수정
- 리코일로 userType 읽어와서 구분
=> Feat#103 qa/vocal search

public/index.html, src/@components/@common/uploadInfo.tsx
=> Feat#101 qa/upload page/hashtag

src/@pages/mainPage.tsx, src/@pages/trackPostPage.tsx
main navigate 를 router에 맞게 수정
(track post 변경사항 미리 push안해서 같이 딸려올라감. 하지만 이것도 제가 맡은 부분이라서 그냥.. 같이 올림 죄송함니다ㅎㅎㅎㅎㅎ)
=> Feat#111 main/route

src/@components/@common/portfolioUpdateModal.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/@common/uploadHeader.tsx, src/@components/vocalProfile/vocalProfileList.tsx, src/@pages/vocalProfilePage.tsx, src/core/constants/pageCategory.ts, src/type/profilePropsType.ts
=> Feat#115 qa/vocal profile page

src/@components/@common/uploadHeader.tsx, src/@components/upload/trackUpload.tsx, src/@components/upload/vocalUpload.tsx, src/core/api/upload.ts, src/recoil/upload.ts, src/type/uploadData.ts
=> Feat#106 qa/upload page/post

src/@components/@common/categoryList.tsx, src/@components/vocalSearch/vocalList.tsx, src/@pages/vocalsPage.tsx, src/core/api/vocalSearch.ts
=> Feat#113 qa/player

package.json, src/@components/@common/portfoliosInform.tsx, src/@pages/trackPostPage.tsx, src/@pages/vocalProfilePage.tsx, src/core/api/download.ts, yarn.lock
- 프로필 페이지에서 타이틀 아이콘이 보이지 않는 문제 해결
- 파일 다운로드 기능 구현
=> Feat#126 qa/js

src/@components/@common/uploadHeader.tsx, src/@components/@common/uploadInfo.tsx, src/@components/upload/trackUpload.tsx, src/@components/upload/vocalUpload.tsx
=> Feat#125 qa/upload page

src/@components/trackSearch/trackList.tsx, src/@pages/producerProfilePage.tsx, src/core/api/producerProfile.ts, src/type/tracksDataType.ts
=> [ fix ] VD001 - 프로듀서 이름 클릭 시 해당 [프로듀서 프로필 페이지-타인]으로 이동

src/@components/trackPost/commentWrite.tsx, src/@pages/trackPostPage.tsx, src/@pages/vocalsPage.tsx, src/core/api/vocalSearch.ts, src/type/vocalsDataType.ts
- 보컬 무한 스크롤 시도
- 트랙 게시글 댓글 자잘한 QA 수정
- 트랙 게시글 댓글 fixed 시도
=> Feat#130 qa/vocals infinite scroll

src/@components/@common/player.tsx, src/@components/@common/uploadHeader.tsx, src/@components/trackSearch/trackList.tsx, src/@pages/producerProfilePage.tsx, src/@pages/trackPostPage.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalProfilePage.tsx, src/@pages/vocalsPage.tsx
=> [ fix ] player 오류 수정

src/@components/@common/categoryHeader.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/trackPost/commentHeader.tsx, src/@components/trackPost/commentWrite.tsx, src/@components/trackPost/eachUserComment.tsx, src/@components/trackPost/userComment.tsx, src/@pages/trackPostPage.tsx, src/core/constants/pageCategory.ts
=> Feat#138 qa/js

src/@components/@common/uploadInfo.tsx
=> [ fix ] type오류 해결

src/@components/@common/player.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/trackSearch/trackList.tsx, src/@components/vocalProfile/vocalProfileList.tsx, src/@pages/producerProfilePage.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalProfilePage.tsx
=> Feat#139 qa/player

src/@components/producerProfile/producerInfos.tsx, src/@pages/producerProfilePage.tsx, src/assets/icon/sleeperAccountIc.svg, src/assets/index.ts, src/recoil/categorySelect.ts
vocal 인지 producer인지 구분하고 프로필 모양 변경
=> [ fix ] vocal profile 모양 수정

src/@pages/trackPostPage.tsx
- open, close, download 버튼 등장 오류 해결
=> Feat#148 qa/js

src/@components/@common/portfoliosInform.tsx, src/@components/trackSearch/trackList.tsx, src/@pages/producerProfilePage.tsx, src/@pages/vocalProfilePage.tsx
- 프로듀서 프로필 2로 박음
- 보컬 프로필 페이지 타이틀 안 뜨는 문제 해결
=> Feat#150 qa/js

src/@components/trackPost/userComment.tsx, src/@components/vocalSearch/vocalList.tsx, src/@pages/trackPostPage.tsx, src/@pages/vocalsPage.tsx
=> [ fix ] 보컬 검색 플레이바 안나오는 오류 해결

src/@pages/trackSearchPage.tsx
=> [ fix ] playBar 오류 수정

src/@components/@common/player.tsx, src/@components/trackPost/eachUserComment.tsx, src/@components/trackPost/userComment.tsx, src/@pages/trackPostPage.tsx
- 플레이어 기능 안된 것들 다 했습니다.
- 트랙 게시물->댓글 플레이어 구현해놨습니다.
- 댓글플레이이는.. 전역변수를 쓰면 안될 것 같아요. trackPostPage에 플레이어가 두개나 있다보니 전역변수가 여러 컴포넌트에서 상태가 
바뀌어서 맘처럼 안되더라고요.. 하면할수록 리팩토링 빨리 해야겠다는 생각뿐ㄴ..
=> Feat#155 qa/common

src/@components/@common/tracksProfileUploadModal.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@pages/producerProfilePage.tsx, src/core/constants/categories.ts, src/utils/common/compareIndex.ts
1. isSameIndex && isNotSameIndex
- index를 비교하는 부분이 많아서 함수로 빼면 좋을거 같다는 생각이 들어서 util-common으로 분기처리해서 구현해봤어요!
2. 불필요코드 
- 깔끔한 성격때문인지(?) 사용하지 않는 변수나 필요없는 변수를 지우는게 속이 편하더라고요....ㅎㅎㅎ 
3. 하드코딩
- 누가 하드코딩 갈겨놔서 순회하는걸로 바꿔놨어요...!! 누군지 모르겠지만 반성하세요!!!!!(ㅋㅋ)
=> Release1.0#167 producer profile page/refactor

src/@components/login/loginInput.tsx
=> Feat#182 login/UI

src/@components/@common/categoryHeader.tsx, src/@components/@common/categoryList.tsx, src/@components/@common/mainHeader.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/@common/tracksProfileUploadModal.tsx, src/@components/@common/uploadInfo.tsx, src/@components/login/loginInput.tsx, src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/profilImageContainer.tsx, src/@components/signUp/sendCodeButton.tsx, src/@components/signUp/signupMessage.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupRole.tsx, src/@components/signUp/verifyButton.tsx, src/@components/trackPost/commentHeader.tsx, src/@components/trackSearch/trackList.tsx, src/@components/trackSearch/trackListHeader.tsx, src/@components/trackSearch/uploadButtonModal.tsx, src/@components/upload/vocalUpload.tsx, src/@components/vocalSearch/vocalListHeader.tsx, src/@pages/loginPage.tsx, src/@pages/mainPage.tsx, src/@pages/signUpPage.tsx, src/style/globalStyle.ts
=> Feat#218 qa/responsive

src/@pages/signUpPage.tsx
회원가입 후 프로필 작성 부분 skip, complete, success화면으로의 연결 구현
=> Qa#224 signUp/complete

src/@components/signUp/signupStepHeader.tsx, src/@pages/signUpPage.tsx
=> Qa#229 sign up/move to login

src/@components/vocalSearch/vocalList.tsx, src/@pages/producerProfilePage.tsx, src/@pages/vocalProfilePage.tsx
=> Qa#234 common/profile path

src/@components/login/loginInput.tsx
=> [ feat ] 회원가입 이동 라우터 설정

src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/continueButton.tsx, src/@components/signUp/sendCodeButton.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupStepHeader.tsx, src/@components/signUp/signupSuccess.tsx, src/@components/signUp/verifyButton.tsx, src/@pages/signUpPage.tsx, src/core/userInfoErrorMessage/verificationCodeInvalidMessage.ts
=> Qa#242 sign up/email fix

src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupStepHeader.tsx, src/@components/signUp/verifyButton.tsx, src/@pages/signUpPage.tsx, src/core/userInfoErrorMessage/verificationCodeInvalidMessage.ts
=> Qa#233 sign up/continue button

src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/continueButton.tsx, src/@components/signUp/sendCodeButton.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupStepHeader.tsx, src/@components/signUp/signupSuccess.tsx, src/@components/signUp/verifyButton.tsx, src/@pages/signUpPage.tsx, src/core/userInfoErrorMessage/verificationCodeInvalidMessage.ts
=> Qa#244 sign up/send code button

src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/conventionCheckBox.tsx, src/@components/signUp/sendCodeButton.tsx, src/@components/signUp/signupProfile.tsx, src/core/api/signUp.ts, src/core/userInfoErrorMessage/emailInvalidMessage.ts
=> Qa#256 profile/text

src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/core/api/trackPost.ts
-> 마지막꺼는 회원가입에서 보내주는 데이터 확인 & 서버 이미지 도메인 확인 후 작업예정
=> Qa#226 main/user info

public/index.html, src/@components/forgotPassword/forgotPasswordInput.tsx, src/utils/hooks/useSendNewPasswordEmail.ts
=> Qa#238 forgot password/message state

src/@components/trackPost/editDropDown.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/trackPostEditPage.tsx, src/@pages/trackPostPage.tsx, src/Router.tsx
=> Qa#236 trackpost/edit

src/@components/signUp/signupSuccess.tsx
- 반응형 수정
- 모달창 구현 -> useModal 커스터마이징 훅 연결
=> Qa#261 sign up/success

src/@components/@common/uploadHeader.tsx, src/@components/@common/uploadInfo.tsx, src/@pages/uploadPage.tsx, src/core/api/upload.ts, src/type/uploadData.ts, src/type/uploadInfoDataType.ts
=> [ fix ] 서버데이터 변경으로 wavFile -> audioFile로 변경 및 에러케이스 수정

src/@components/main/produderBriefInfo.tsx, src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupProfile.tsx, src/assets/icon/profileHashtagXIc.svg, src/assets/index.ts
=> Qa#258 profile/hashtag

src/@components/@common/profileWarning.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/signupMessage.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupProfile.tsx, src/assets/icon/profileHashtagXIc.svg, src/assets/index.ts
=> Qa#259 profile/warning

src/@components/@common/profileWarning.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/signupMessage.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupProfile.tsx, src/assets/icon/profileHashtagXIc.svg, src/assets/index.ts, src/core/api/profile.ts
=> Qa#268 profile/patch profile

src/@components/@common/mainHeader.tsx, src/@components/@common/profileEditInfo.tsx, src/@components/@common/profileWarning.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/signUp/SignupEmailPassword.tsx, src/@components/signUp/signupMessage.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@components/signUp/signupProfile.tsx, src/assets/icon/profileHashtagXIc.svg, src/assets/index.ts, src/core/api/profile.ts
=> Qa#260 profile/profil edit

src/@components/trackPost/eachUserComment.tsx, src/@components/trackPost/userComment.tsx, src/core/api/trackPost.ts
=> Qa#285 track post/comment update

src/@components/trackPost/editDropDownComment.tsx, src/@components/trackPost/userComment.tsx, src/core/api/trackPost.ts
=> Qa#287 track post/comment delete

src/@components/trackPost/commentUpdate.tsx, src/@components/trackPost/commentWrite.tsx, src/@components/trackPost/userComment.tsx
=> Qa#293 comment/post bug

src/@pages/producerProfilePage.tsx
Reverts Track1-client/client#296
=> Revert "Qa#282 producer profile/data"

package.json, src/@pages/trackPostPage.tsx, src/core/api/trackPost.ts, yarn.lock
[다운로드 기본 틀](https://jun711.github.io/aws/download-from-amazon-s3-buckets-using-javascript/)
[다운로드 responseType 변경해주기](https://gaemi606.tistory.com/entry/React-%ED%8C%8C%EC%9D%BC-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C)
=> Qa#295 track post/download

package.json, src/@pages/trackPostPage.tsx, src/core/api/trackPost.ts, yarn.lock
=> Qa#300 download/bugs

src/@components/signUp/producerUploadModal.tsx, src/@components/signUp/profilImageContainer.tsx, src/@components/signUp/signupSuccess.tsx
=> Qa#304 sign up/bugs

src/@components/@common/categoryList.tsx, src/@components/@common/player.tsx, src/@components/login/loginInput.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/trackPost/userComment.tsx, src/@components/trackSearch/trackList.tsx, src/@components/trackSearch/uploadButtonModal.tsx, src/@components/vocalSearch/vocalList.tsx, src/@pages/trackPostPage.tsx, src/mocks/categoryDummy.json
-> 업로드 페이지, 포트폴리오 페이지 제외 반응형 구현 완료
=> Qa#306 common/responsive

src/@pages/producerProfilePage.tsx
Reverts Track1-client/client#312
=> Revert "Qa#297 producer profile/data"

src/@components/@common/categoryHeader.tsx, src/@components/@common/categoryList.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/resetPassword/resetPasswordInput.tsx, src/@pages/resetPasswordPage.tsx, src/recoil/categorySelect.ts
=> Qa#314 header/bugs

src/@components/@common/profileEditInfo.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/profileEdit/producerProfileEditTitle.tsx, src/@pages/producerProfilePage.tsx, src/@pages/profileEditPage.tsx, src/@pages/vocalProfilePage.tsx, src/core/api/myPage.ts
프로필 수정 페이지의 api-patch 수정 좀 했습니다
=> Qa#291 common/api patch

src/@components/@common/portfoliosInform.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/@pages/producerProfilePage.tsx, src/@pages/vocalProfilePage.tsx
=> Qa#317 portfolio/bugs

src/@components/@common/backButton.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/@common/profileEditInfo.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/profileEdit/producerProfileEditTitle.tsx, src/@components/profileEdit/profileEditHeader.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@pages/profileEditPage.tsx
=> Qa#323 profile/bugs

src/@components/signUp/conventionCheckBox.tsx, src/@components/signUp/profilImageContainer.tsx, src/@components/signUp/signupNicknameConvention.tsx, src/@pages/signUpPage.tsx, src/type/signUpStepTypes.ts
=> Qa#325 signup/bugs

src/@pages/trackSearchPage.tsx, src/@pages/vocalProfilePage.tsx, src/@pages/vocalsPage.tsx
#340 vocal profile 무한스크롤 오류 해결
=> Qa#340 vocal profile/infinite scroll

src/@components/@common/backButton.tsx, src/@components/@common/categoryHeader.tsx, src/@components/@common/categoryList.tsx, src/@components/@common/portfolioUpdateModal.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/trackSearch/trackList.tsx, src/@pages/producerProfilePage.tsx, src/@pages/trackPostPage.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalProfilePage.tsx, src/@pages/vocalsPage.tsx
=> [ fix ] 플레이어 오류 해결

src/@components/trackSearch/trackList.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalProfilePage.tsx
=> Qa#348 vserror

src/@components/@common/backButton.tsx, src/@components/@common/categoryList.tsx, src/@components/signUp/signUpBackButton.tsx, src/@pages/trackSearchPage.tsx, src/core/api/trackSearch.ts
=> Qa#350 filtering/reverse

src/@components/@common/profileEditInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/producerProfile/producerPortFolioList.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@components/vocalProfile/vocalProfileList.tsx, src/@pages/producerProfileEditPage.tsx, src/@pages/producerProfilePage.tsx, src/@pages/vocalPortfolioEditPage.tsx, src/@pages/vocalProfileEditPage.tsx, src/@pages/vocalProfilePage.tsx
=> Qa#353 common/patch fix

src/@components/@common/categoryList.tsx, src/@components/upload/uploadHeader.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalsPage.tsx, src/core/api/upload.ts
trackSearch & vocalSearch 필터링 문제 모두 해결했습니다.
=> Qa#364 track search/filter

src/@components/@common/backButton.tsx, src/@components/@common/portfolioUpdateModal.tsx, src/@components/@common/profileEditInfo.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/trackPostEditPage.tsx, src/@pages/trackPostPage.tsx, src/@pages/vocalProfileEditPage.tsx, src/@pages/vocalProfilePage.tsx, src/core/api/trackPost.ts, src/type/producerProfile.ts
프로필 & 포트폴리오 & 게시물 수정하는 부분 오류 부분적으로 해결
=> [ fix ] patch api오류 해결

src/@components/profileEdit/producerProfileEditTitle.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/producerProfileEditPage.tsx, src/@pages/producerProfilePage.tsx, src/@pages/trackPostEditPage.tsx, src/@pages/vocalPortfolioEditPage.tsx, src/@pages/vocalProfileEditPage.tsx
=> [ feat ] 프로필 수정 서버 변경 반영

src/style/globalStyle.ts
=> [ design ] 가로 스크롤 없도록 반응형 수정

src/@components/trackPost/commentUpdate.tsx, src/@components/trackPost/userComment.tsx
=> Qa#386 comment

src/@components/producerProfile/producerInfos.tsx, src/@pages/producerProfilePage.tsx
=> Qa#389 producer/profile

src/@components/@common/backButton.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/profileEdit/profileEditHeader.tsx, src/@components/upload/uploadHeader.tsx, src/@pages/forgotPasswordPage.tsx, src/@pages/loginPage.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/trackPostEditPage.tsx, src/@pages/trackPostPage.tsx, src/@pages/vocalPortfolioEditPage.tsx
=> Qa#392 back btn/bugs

src/@components/@common/conventionModal.tsx
=> [ style ] modal 맨 앞으로 가도록 style 수정

src/@components/@common/profileEditInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/signUp/signupProfile.tsx, src/@components/upload/trackUpload.tsx, src/@components/upload/uploadInfo.tsx, src/@pages/vocalPortfolioEditPage.tsx, src/@pages/vocalProfileEditPage.tsx, src/@pages/vocalProfilePage.tsx, src/style/globalStyle.ts, src/utils/convention/checkHashtagLength.ts, src/utils/uploadPage/uploadImage.ts
=> Qa#394 hashtag/bugs

src/@components/@common/profileEditInfo.tsx, src/@components/@common/profileWarning.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/profileEdit/profileEditHeader.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@components/signUp/signupProfile.tsx, src/@components/trackPost/hashTag.tsx, src/@components/upload/uploadInfo.tsx, src/@pages/loginPage.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/vocalPortfolioEditPage.tsx
=> Qa#400 edit page/bugs

src/@components/@common/categoryHeader.tsx, src/@components/@common/categoryList.tsx, src/@components/@common/mainHeader.tsx, src/@components/@common/profileEditInfo.tsx, src/@components/login/loginInput.tsx, src/@components/profileEdit/producerProfileEditTitle.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx, src/@components/trackPost/hashTag.tsx, src/@components/trackPost/userComment.tsx, src/@components/trackSearch/trackList.tsx, src/@components/vocalSearch/vocalList.tsx, src/@pages/signUpPage.tsx, src/@pages/trackPostPage.tsx, src/Router.tsx, src/utils/common/isLogined.ts, src/utils/common/privateRoute.tsx
=> Qa#402 common/private

src/@components/@common/categoryList.tsx, src/core/api/vocalSearch.ts
=> [ fix ] 보컬서칭 trackSearching 필터링 기능 구현

src/@components/producerProfile/producerInfos.tsx, src/@pages/trackPostPage.tsx
기획과의 상의 후 마이페이지에서의 back 버튼을 메인 페이지로 바꿈.
=> Qa#410 my page/back

src/@components/trackPost/commentUpdate.tsx, src/@components/trackPost/commentWrite.tsx, src/@components/trackPost/eachUserComment.tsx, src/@components/trackPost/userComment.tsx
=> Qa#413 comment/profile image

src/@components/trackPost/commentUpdate.tsx, src/@components/trackPost/commentWrite.tsx, src/@components/trackPost/eachUserComment.tsx, src/@components/trackPost/userComment.tsx, src/@pages/producerProfilePage.tsx, src/@pages/vocalProfilePage.tsx
=> Qa#416 vocal profile/infinite

src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx
넘어가면 말 줄임표 이용함. 
width: 22.5rem;  //width 고정
white-space: nowrap; // 영역 넘어도 줄바꿈 안 되도록
text-overflow: ellipsis; // text ...말줄임표 추가
overflow: hidden; // 영역 넘은부분은 안 보이도록
=> Qa#421 main page/UI

src/@components/@common/tracksProfileUploadModal.tsx, src/@components/main/produderBriefInfo.tsx, src/@components/main/vocalBriefInfo.tsx, src/@components/signUp/producerUploadModal.tsx, src/@components/upload/uploadHeader.tsx, src/@pages/uploadPage.tsx
이전페이지 값을 state로 넘겨줘서 
이전에 회원가입 페이지에 있었다면 다른 navigate 값을 주는 방식으로 구현했습니다.
=> Qa#429 sign up/complete

src/@components/profileEdit/producerProfileEditTitle.tsx, src/@components/profileEdit/vocalProfileEditTitle.tsx
=> Qa#435 profile edit/name

src/@components/vocalSearch/vocalList.tsx
=> [ style ] 보컬이름이 길어질때 css 수정

src/@pages/trackPostPage.tsx
=> [ feat ] state값 추가로 제대로 이동하도록 함.

src/core/api/vocalProfile.ts
=> [ etc ] refresh 토큰 테스트

src/@components/@common/portfolioUpdateModal.tsx, src/@components/@common/portfoliosInform.tsx, src/@components/producerProfile/producerInfos.tsx, src/@components/trackSearch/uploadButtonModal.tsx, src/@components/upload/uploadHeader.tsx, src/@pages/mainPage.tsx, src/@pages/producerProfileEditPage.tsx, src/@pages/producerProfilePage.tsx, src/@pages/trackPostEditPage.tsx, src/@pages/trackPostPage.tsx, src/@pages/uploadPage.tsx, src/@pages/vocalPortfolioEditPage.tsx, src/@pages/vocalProfileEditPage.tsx, src/@pages/vocalProfilePage.tsx, src/core/api/trackPost.ts, src/core/api/upload.ts, src/core/api/vocalSearch.ts
trackPost & Profile부분 오류들 모두 수정했습니다.
=> Qa#449 common/post fix

src/core/api/trackSearch.ts
=> [ etc ] track search api 변경 테스트

src/core/api/delete.ts
=> [ etc ] delete API 변경 테스트

src/core/api/logout.ts, src/core/api/signUp.ts
=> [ etc ] logout, signup API 테스트

src/core/api/signUp.ts
=> [ etc ] signup api 추가 테스트

src/core/api/producerProfile.ts, src/core/api/vocalProfile.ts
=> [ etc ] profile api 변경 테스트

src/core/api/myPage.ts, src/core/api/resetPassword.ts, src/core/api/trackUpload.ts
=> [ etc ] mypage, resetPassword API 변경 테스트

src/core/api/profile.ts, src/core/api/upload.ts, src/core/api/vocalSearch.ts
=> [ etc ] profile, upload, vocalsearch api 테스트

src/@pages/vocalsPage.tsx
=> [ fix ] 리로드 잘못된 코드 수정

src/@components/@common/portfolioUpdateModal.tsx, src/core/api/delete.ts
=> [ fix ] 보컬 서칭 삭제 안되는 이슈 해결

src/@components/trackPost/eachUserComment.tsx
=> [ feat ] hover시 이미지 추가

src/@components/@common/categoryList.tsx, src/@components/trackPost/eachUserComment.tsx
vocal 계정으로 track-post 들어갈 때, upload 버튼 클릭시 alert창 띄움.
```
blockAccess()
? navigate("/login")
: userType === "producer"
? setOpenModal(true)
: alert("해당 기능은 프로듀서로 로그인 후 이용해주세요.");
```
userType으로 검사 후 modal을 띄울지, alert를 띄울지 삼항연산자로 지정
=> Qa#473 vocal/track post

src/@components/upload/uploadInfo.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/vocalPortfolioEditPage.tsx
=> Qa#425 upload/UI

src/core/api/trackPost.ts
=> [ etc ] track download api 테스트

src/core/api/trackSearch.ts
=> [ feat ] trackPost api 헤더 쿠키 설정

src/@components/trackPost/eachUserComment.tsx, src/@components/upload/uploadInfo.tsx, src/@pages/trackPostEditPage.tsx
=> Qa#491 test/etc

src/@components/trackPost/userComment.tsx
=> Qa#489 etc

src/@components/@common/profileEditInfo.tsx, src/@components/signUp/signupProfile.tsx, src/utils/hooks/useTextareaHeight.ts
signUpProfile/ profileEditInfo / trackPostEditPage / producerPortfoiloEditPage/ uploadInfo 
signUpProfile/
profileEditInfo/
uploadInfo
=> 완료 
나머지 2개 해야함
=> Qa#501 description

src/@components/signUp/SignupEmailPassword.tsx, src/@pages/signUpPage.tsx
=> [ fix ] 크롬 자동저장 막기

src/@components/@common/profileEditInfo.tsx, src/@components/signUp/signupProfile.tsx, src/utils/hooks/useTextareaHeight.ts
Reverts Track1-client/client#504
=> Revert "Qa#501 description"

src/@components/@common/profileEditInfo.tsx, src/utils/hooks/useTextareaHeight.ts
=> [ feat ] profileEditInfo 디스크립션 수정

src/@components/signUp/signupProfile.tsx, src/@components/upload/uploadInfo.tsx, src/@pages/producerPortfolioEditPage.tsx, src/@pages/trackPostEditPage.tsx, src/utils/hooks/useTextareaHeight.ts
얏호!얏호!
signUpProfile / trackPostEditPage / producerPortfoiloEditPage/ uploadInfo
디스크립션 완성!
=> Qa#519 upload/sign up/re merge

src/@components/@common/portfoliosInform.tsx
=> [ fix ] blackIcon 조건 변경

src/@components/@common/portfolioUpdateModal.tsx
=> [ fix ] 프로듀서,보컬, 포트폴리오, 보컬서칭 별로 삭제 조건추가

src/@components/login/loginInput.tsx
=> [ fix ] 패스워드 저장 로직 수정

src/recoil/forgotPasswordToken.ts
=> [ fix ] 페이지가 이동하면서 recoil 값이 초기화되는 이슈 해결

package.json
=> [ feat ] sourceMap 감추기

src/@components/@common/portfoliosInform.tsx
=> [ fix ] 뷰모어 버튼 안 뜨는 문제 해결

src/@components/forgotPassword/forgotPasswordInput.tsx, src/@pages/resetPasswordPage.tsx, src/Router.tsx, src/core/api/common/axios.ts
=> Qa#550 axios/refresh

public/index.html, src/@components/trackPost/userComment.tsx
=> Qa#551 common/UI fix

src/@pages/resetPasswordPage.tsx, src/core/api/validateResetPasswordToken.ts
=> [ etc ] resetPassword 페이지 렌더링 될때 useParms를 이용해 토큰값 전달

src/@components/forgotPassword/forgotPasswordInput.tsx
=> [ etc ] 기능해결로 인한 알림창 삭제

src/@components/producerProfile/producerPortFolioList.tsx
=> Qa#558 portfolio/hover

src/@components/@common/footer.tsx, src/@pages/errorPage.tsx
=> [ fix ] 어드민 이메일 주소 수정

src/@pages/trackPostPage.tsx
url을 직접 치고 들어갔을 때 데이터를 못 받아오는 오류를 해결했습니다.
=> [ fix ] trackPostPage 접근 오류 수정

package.json, src/utils/hooks/useTextareaHeight.ts
=> Qa#564 description/UI

src/@pages/trackPostPage.tsx
=> [ fix ] 로그인 하지 않고 프로듀서 프로필 페이지 접근 시 음악 멈추도록 구현

public/index.html
=> [ feat ] ga 태그 삽입

src/@pages/vocalProfilePage.tsx
=> [ fix ] vocalProfilePage 접근 오류 수정

src/@pages/producerProfilePage.tsx
=> [ fix ] 프로듀서 프로필 페이지 경로 수정

src/@components/signUp/SignupEmailPassword.tsx
=> [ fix ] 회원가입 비밀번호 한글 입력 안 되도록 수정

src/core/userInfoErrorMessage/passwordInvalidMessage.ts, src/utils/errorMessage/checkPasswordForm.ts
=> Qa#578 sign up/special

src/core/userInfoErrorMessage/passwordInvalidMessage.ts
=> [ etc ] 비밀번호 오류 메시지 수정

public/index.html
=> [ feat ] GTM코드 삽입

src/@components/@common/eventModal.tsx, src/@pages/mainPage.tsx, src/assets/icon/eventModalIc.svg, src/assets/index.ts, src/recoil/conventionModal.ts
=> Feat#584 popup

src/@components/@common/backButton.tsx, src/@components/@common/filter.tsx, src/@components/@common/header.tsx, src/@components/login/loginForm.tsx, src/@components/main/mypageButton.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeaderNav.tsx, src/@pages/loginPage.tsx, src/@pages/trackSearchPage.tsx
=> Feat#733 common/qa

src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeaderNav.tsx, src/@pages/trackSearchPage.tsx, src/@pages/vocalSearchPage.tsx
=> [ fix ] 네비게이션 설정 및 텍스트 스타일 수정

src/@components/@common/hashtag/hashtagInput.tsx, src/@components/@common/header.tsx, src/@components/producerProfile/index.tsx, src/@components/profileEdit/index.tsx, src/@components/profileEdit/profileHashtagEdit.tsx, src/@components/signUp/signupProfile.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx, src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx, src/@components/upload/hashtagInfo.tsx, src/@components/upload/uploadBody.tsx, src/@components/upload/uploadInfoBox.tsx, src/@pages/trackSearchPage.tsx, src/api/common/client.ts, src/hooks/common/useHashtagInput.ts, src/hooks/queries/mypage.ts, src/hooks/queries/tracks.ts
=> Feat#748 common/hmh qa

src/api/common/client.ts
=> [ fix ] axios 헤더 설정 변경

src/@components/trackPost/audioCategory.tsx, src/@components/trackPost/audioDescription.tsx, src/@components/trackPost/audioHashtags.tsx, src/@components/trackPost/editDropDown.tsx, src/@components/trackPost/showMore.tsx, src/@components/upload/uploadBody.tsx, src/type/tracks.ts
=> [ fix ] 업로드 수정 초기데이터 셋팅값 전달 및 데이터 변수명 수정
